### ISSUE TITLE
Cannot Get Working on Codesandbox

### ISSUE THREAD

**Issue by jrock2004** [brandynbennett/ember-inputmask#109]
I want to create a ember sandbox to do some testing, but I am getting `Error: Compile Error: one-way-input-mask is not a helper`. Not sure if I have not installed something that is required that I am missing. you can see the sandbox here https://codesandbox.io/s/my-app-hhjmm

```
<h1>Sample</h1>

{{one-way-input-mask
  mask="aa-99-**"
  class="docs-border docs-border-grey"
}}
```

"ember-inputmask": "^0.9.1",

**Comment by brandynbennett** [comment]
@jrock2004 I tried to take a look at the sandbox but I don't see anything. I can't even get a hello world to display via the `application.hbs`.

**Comment by jrock2004** [comment]
@brandynbennett sorry I was on vacation. You can open devtools to see the console error that is breaking it. Here is a new link https://codesandbox.io/s/my-app-hhjmm

![image](https://user-images.githubusercontent.com/655716/62165331-2f791080-b2ec-11e9-8093-cdfce7a3030f.png)

**Comment by brandynbennett** [comment]
I can't get the sandbox to even load that far for me. I see this:
<img width="562" alt="Screen Shot 2019-08-17 at 2 24 18 PM" src="https://user-images.githubusercontent.com/4146629/63216940-cde1e000-c0fa-11e9-9402-151380eca039.png">

**Comment by jrock2004** [comment]
Yeah I been trying to create a new sandbox to use. Not sure why that one corrupted

**Comment by jrock2004** [comment]
Well I took a look again and now it seems to be working just fine. Not sure what has changed. Maybe issue was on codesandbox side
