### ISSUE TITLE
Upgrade Input Mask

### ISSUE THREAD

**Issue by jrock2004** [brandynbennett/ember-inputmask#127]
From the looks of input mask itself. The latest non-beta version is 5.0.3. Any plans on upgrading that version?

**Comment by brandynbennett** [comment]
That's awesome. Didn't realize it was out now. I would like to see this addon on the latest. I would very much welcome a PR with this change.

**Comment by jrock2004** [comment]
@brandynbennett I started looking but it looks like there is some app imports that you are doing that no longer comes in 5.x

**Comment by brandynbennett** [comment]
Bumped in v0.11.0
