### ISSUE TITLE
No longer maintained suggestion

### ISSUE THREAD

**Issue by cah-briangantzler** [brandynbennett/ember-inputmask#158]
So sorry to see this is no longer maintained.

I was contemplating taking over and updating to octane, maybe a modifier, and came across this repo https://github.com/sinankeskin/ember-inputmask Since this repo also fronts the same package https://github.com/RobinHerbots/Inputmask the conversion has been pretty easy. Especially like the modifier version.

What I might suggest you do is instead of finding a new maintainer for this repo, update the readme to point users to the replacement repo of https://github.com/sinankeskin/ember-inputmask

Thanks

**Comment by brandynbennett** [comment]
Good call. Went ahead and did that. Thanks!
