### ISSUE TITLE
Cannot set class on one-way-input-mask

### ISSUE THREAD

**Issue by happydude** [brandynbennett/ember-inputmask#65]
Hello, I noticed starting with 0.6.4 that setting class on the one-way-input-mask component causes an error. We use bootstrap on our project so we set the class to form-control to match other inputs.

{{one-way-input-mask class="form-control"}}

Generates the message "Assertion Failed: You cannot use class as an attributeBinding, use classNameBindings instead."

I can verify it worked in 0.6.3, if I remove class then 0.6.4 works minus the bootstrap styling

**Comment by brandynbennett** [comment]
Sorry about that. Stupid mistake on my part. Fixing now.

**Comment by happydude** [comment]
Thanks!
