### ISSUE TITLE
Hitting enter in a one-way-input-mask throws "TypeError: Ember.get(...) is not a function"

### ISSUE THREAD

**Issue by xm** [brandynbennett/ember-inputmask#68]
The error is caused by trying to call a function that does not exist in `keyUp`:

https://github.com/brandynbennett/ember-inputmask/blob/17717ba39864513b76a004d1eaea62b76dc4d63d/addon/components/one-way-input-mask.js#L148-L157

I read the documentation and searched the code to see if there was any place this was being used and it doesn't appear so. Can this be deleted entirely? Or should it just be changed to:

```
  keyUp(event) {
    let method = get(this, `keyEvents.${event.keyCode}`);
    if (method) {
      tryInvoke(this, method, [event.target.value]);
    }
  },
```

**Comment by brandynbennett** [comment]
@xm Thanks for pointing this out. I don't think we can remove it, because I don't know if there are apps out there who depend on it. 

I pushed up a fix in v0.6.6
