### ISSUE TITLE
Change value in response to update action on one way input to something different then user typed?

### ISSUE THREAD

**Issue by jcope2013** [brandynbennett/ember-inputmask#78]
Is it possible to change the value in the update depending on the value the user typed to something else? The issue I am seeing is if I change the number in the update action to something different then the user typed, it only changes the value in the input the first time.

Example: if you change it to a value greater then 15, the input value changes to 15 which is what I expect but then when the input value is 15 add a 5 to it so it is 155, the update action triggers again and changes the underlying value to 15 but the input is stuck in 155 instead of the correct value of 15, it is now out of the sync with the value

https://ember-twiddle.com/47ce7d4475f7ce89f1c9158373160091?openFiles=controllers.application.js%2C

I think a similar issue is described here which the one way-input was based off of

https://github.com/DockYard/ember-one-way-controls/issues/100
https://github.com/DockYard/ember-one-way-controls/pull/101

**Comment by scottkidder** [comment]
I just dealt with this. I ended up using

`Inputmask.setValue('input', value);`

per https://github.com/RobinHerbots/Inputmask#setvalue

**Comment by jcope2013** [comment]
are you calling that from your update action?

**Comment by scottkidder** [comment]
Yes, in my case I am enforcing numeric maximum (without passing the max option to Inputmask) in my update action and then using setValue to rewrite the value into the input correctly.

I think this aligns better with DDAU and maybe should be the default in some form?

**Comment by scottkidder** [comment]
https://ember-twiddle.com/13f5a773f9a0ca9503977b821c74efb4?openFiles=twiddle.json%2C

- Updated to ember-inputmask v0.7.0
- Used Inputmask.setValue in the update action

**Comment by brandynbennett** [comment]
Ya, this is a bug. Thanks for pointing this out and thanks @scottkidder for showing a workaround. I'll get a fix made

**Comment by brandynbennett** [comment]
@jcope2013 @scottkidder pushed a fix in 0.7.1

**Comment by scottkidder** [comment]
@brandynbennett Works great in 0.7.1, thanks. :tada:
