### ISSUE TITLE
Programatically Add Input Mask

### ISSUE THREAD

**Issue by MatthewPringle** [brandynbennett/ember-inputmask#80]
Previously I used to add an input mask using

var mask = this.$( 'input' );
 
if ( mask.length ) {

            mask.inputmask({
                mask: '1 / y',
                alias: 'date',
                separator: ' / ',
                placeholder: 'MM / YYYY',
                showMaskOnHover: false,
                showMaskOnFocus: false,
                yearrange: {
                    minyear: 0,
                    maxyear: 9999
                }
          });
 
}

Now it seems I need to use a .hbs template. Is there a way of doing it the older way as I need more control over the input and mask.

**Comment by brandynbennett** [comment]
So the latest versions no longer use the jquery plugin. However you should be able to pass any options you want to Inputmask.js via the options argument

```hbs
{{one-way-input-mask mask='1 / y' options=(hash alias='date'
  separator='/'
  yearrange=(hash minyear=0 maxyear=9999))}}
```
