### ISSUE TITLE
no placeholder with currency mask

### ISSUE THREAD

**Issue by oliverlj** [brandynbennett/ember-inputmask#91]
Hi,

I can't show a placeholder text with a curreny mask or a one-way-currency-mask.

As a workaround, i use a number mask for the moment 

            {{one-way-number-mask
              class="sizefull p-l-22 p-r-22"
              name="price"
              options=(hash autogroup=true groupSeparator=',' digits=2 digitsOptional=false suffix=" €" placeholder='0')
              placeholder=(t 'sneaker.edit.input.placeholder.price')
              type="text"
              update=(action (mut model.price))
              value=model.price
            }}

**Comment by brandynbennett** [comment]
I got it to work by setting `clearMaskOnLostFocus=true` in the `options` hash. The default mask for `currency` in Inputmask.js has this set to false.

```
{{one-way-currency-mask
  options=(hash prefix='£' clearMaskOnLostFocus=true)
  placeholder='foo'
  class='docs-border docs-border-grey'}}
```
