### ISSUE TITLE
Breaks on ember >= 3.6

### ISSUE THREAD

**Issue by lucacorti** [brandynbennett/ember-inputmask#93]
There is some infinite recursion which breaks `ember-inputmask` and also makes the resolver import fail, making the hosting app break.

```
too much recursion[Learn More] metal.js:751
CPGETTER_FUNCTION
metal.js:751
DependencyLib.extend
inputmask.dependencyLib.js:238
DependencyLib.extend
inputmask.dependencyLib.js:250
DependencyLib.extend
inputmask.dependencyLib.js:250
DependencyLib.extend
inputmask.dependencyLib.js:250
DependencyLib.extend
inputmask.dependencyLib.js:250
DependencyLib.extend
inputmask.dependencyLib.js:250
DependencyLib.extend
[...]
Error: Could not find module `ember-resolver` imported from `maskedtest/resolver

**Comment by brandynbennett** [comment]
@lucacorti I'm having trouble reproducing this issue. I tried it on a new 3.6 Ember app with the latest ember-inputmask (0.8.5). Which versions of the addon are you using? Is this happening at build time or runtime?

**Comment by ttill** [comment]
I am also facing this bug using ember-inputmask 0.8.5 and Ember 3.6. Error occurs at runtime.

**Comment by ttill** [comment]
Fixed in Ember 3.6.1.
See: emberjs/ember.js#17190

**Comment by jacobq** [comment]
@brandynbennett you probably got v3.6.1 hot off the press :)
@lucacorti Can you confirm correct behavior in v3.6.1 (and close this)?

**Comment by lucacorti** [comment]
@jacobq Yes it works, thank you and sorry for the noise.
